# Generated by Django 5.0 on 2023-12-11 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videopage', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Video',
        ),
    ]
