# Generated by Django 5.0 on 2023-12-12 23:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0006_alter_video_options'),
        ('videopage', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preview_image_path', models.ImageField(blank=True, upload_to='VideoPreview/')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.video')),
            ],
            options={
                'verbose_name': 'Video Preview',
                'verbose_name_plural': 'Video Previews',
            },
        ),
        migrations.DeleteModel(
            name='VideoPreview',
        ),
    ]
