# Generated by Django 5.0 on 2023-12-14 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videopage', '0005_videopreview_delete_videopage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VideoPreview',
        ),
    ]
