# Generated by Django 5.0 on 2023-12-15 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('homepage', '0009_rename_preview_image_video_preview_file'),
        ('videopage', '0006_delete_videopreview'),
    ]

    operations = [
        migrations.CreateModel(
            name='list_Video',
            fields=[
                ('video_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='homepage.video')),
            ],
            bases=('homepage.video',),
        ),
    ]
