# Generated by Django 5.0 on 2023-12-16 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videopage', '0007_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='list_Video',
        ),
    ]
