# Generated by Django 5.0.1 on 2024-01-18 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("homepage", "0010_userdata"),
        ("videopage", "0010_video_title_video_uploader"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="video",
            options={"verbose_name": "Video", "verbose_name_plural": "Videos"},
        ),
        migrations.AddField(
            model_name="video",
            name="homepage_video",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="homepage.video",
            ),
        ),
    ]
