# Generated by Django 5.0.1 on 2024-01-15 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('homepage', '0010_userdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoFrames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_frames_60', models.BooleanField(default=False)),
                ('has_frames_4', models.BooleanField(default=False)),
                ('total_frames_60', models.IntegerField(default=0)),
                ('total_frames_4', models.IntegerField(default=0)),
                ('frame_number', models.IntegerField(default=0)),
                ('video_frames_total', models.IntegerField(default=0)),
                ('frame_folder_path', models.CharField(max_length=255)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.video')),
            ],
        ),
    ]
