# Generated by Django 5.0.1 on 2024-01-15 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='videoframes',
            options={'verbose_name_plural': 'Video Frames'},
        ),
    ]
