# Generated by Django 5.0.1 on 2024-01-15 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0002_alter_videoframes_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoframes',
            name='frame_folder_path_4',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='videoframes',
            name='frame_folder_path_60',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='videoframes',
            name='frame_folder_path',
            field=models.CharField(default='', max_length=255),
        ),
    ]
