# Generated by Django 5.0.1 on 2024-01-18 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0003_videoframes_frame_folder_path_4_and_more'),
        ('homepage', '0010_userdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='FrameAnnotations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frame_type', models.CharField(default='', max_length=10)),
                ('frame_number', models.IntegerField(default=0)),
                ('rank', models.CharField(default='', max_length=20)),
                ('is_annotated', models.BooleanField(default=False)),
                ('annotator', models.CharField(default='', max_length=255)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.video')),
            ],
            options={
                'verbose_name_plural': 'Frame Annotations',
            },
        ),
    ]
