# Generated by Django 5.0.1 on 2024-01-24 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0004_frameannotations'),
    ]

    operations = [
        migrations.AddField(
            model_name='frameannotations',
            name='progress',
            field=models.IntegerField(default=0),
        ),
    ]
