# Generated by Django 5.0.1 on 2024-01-24 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0005_frameannotations_progress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='frameannotations',
            name='progress',
        ),
    ]
