# Generated by Django 5.0 on 2023-12-11 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='edited_time',
            field=models.DateTimeField(null=True),
        ),
    ]
