# Generated by Django 5.0 on 2023-12-12 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_remove_video_edited_time_video_edit_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='video_file',
            field=models.FileField(default=0, upload_to='Video/'),
            preserve_default=False,
        ),
    ]
