# Generated by Django 5.0 on 2023-12-12 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_video_video_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='edited',
            new_name='annotated',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='edit_time',
            new_name='annotation_time',
        ),
    ]
