# Generated by Django 5.0 on 2023-12-14 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0006_alter_video_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='preview_image',
            field=models.ImageField(blank=True, null=True, upload_to='PreviewImage/'),
        ),
    ]
