# Generated by Django 5.0 on 2023-12-14 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0008_alter_video_preview_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='preview_image',
            new_name='preview_file',
        ),
    ]
