# Generated by Django 5.0.1 on 2024-01-24 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0010_userdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='progress',
            field=models.IntegerField(default=0),
        ),
    ]
